OpenBanking-Brasil/openapi

- account/doc/1.0.3.json
Atualização do JSON da API Account.
> Gh pages dev para gh pages

- .github/workflows/deploy.yml
Inclusão de debug e ajuste no fluxo atual.
> Debugs e ajustes no fluxo

- openbanking-ui.css
- swagger-apis/accounts/index.html
- swagger-apis/acquiring-services/index.html
- swagger-apis/admin/index.html
- swagger-apis/capitalization-bonds/index.html
- swagger-apis/channels/index.html
- swagger-apis/common/index.html
- swagger-apis/consents/index.html
- swagger-apis/credit-cards/index.html
- swagger-apis/customers/index.html
- swagger-apis/exchange/index.html
- swagger-apis/financings/index.html
- swagger-apis/insurances/index.html
- swagger-apis/investments/index.html
- swagger-apis/invoice-financings/index.html
- swagger-apis/loans/index.html
- swagger-apis/participants/index.html
- swagger-apis/payments/index.html
- swagger-apis/pension/index.html
- swagger-apis/products-services/index.html
- swagger-apis/resources/index.html
- swagger-apis/unarranged-accounts-overdraft/index.html
- Ajustar CSS da estrutura dos repositórios Open Api para estilizar o aviso de draft no SwaggerHub.
- Ajustar link de documentação oficial
> fix(Open Api): ORB-486

- dictionary/paymentsGetConsentsConsentId_v1.csv
- dictionary/paymentsGetPixPaymentsPaymentId_v1.csv
- dictionary/paymentsPatchPixPayments_v1.csv
- dictionary/paymentsPostConsents_v1.csv
- dictionary/paymentsPostPixPayments_v1.csv
- swagger-apis/payments/1.2.0.yml
- swagger-apis/payments/index.html
**feat(Payments): [PE01]**
- Adicionando EndToEndId no endpoint de [POST] request - pix/payments
- Adicionando itens de enum do status code 422: PARAMETRO_NAO_INFORMADO, PARAMETRO_INVALIDO
> feat(Payments): [PE01] - Adicionando EndToEndId; Adicionando itens no elemento title; code e details

- dictionary/paymentsGetConsentsConsentId_v2.csv
- dictionary/paymentsGetPixPaymentsPaymentId_v2.csv
- dictionary/paymentsPatchPixPaymentsPaymentId_v2.csv
- dictionary/paymentsPostConsents_v2.csv
- dictionary/paymentsPostPixPayments_v2.csv
- swagger-apis/acquiring-services/1.0.0-rc1.0.yml
- swagger-apis/admin/1.0.2.yml
- swagger-apis/capitalization-bonds/1.0.0-rc1.0.yml
- swagger-apis/central-directory/index.html
- swagger-apis/channels/1.0.2.yml
- swagger-apis/credit-cards/2.0.1.yml
- swagger-apis/exchange/1.0.0-rc1.0.yml
- swagger-apis/insurances/1.0.0-rc1.0.yml
- swagger-apis/investments/1.0.0-rc1.0.yml
- swagger-apis/payments/2.0.0-rc1.0.yml
- swagger-apis/payments/index.html
- swagger-apis/pension/1.0.0-rc1.0.yml
- swagger-apis/products-services/1.0.2.yml
- swagger-apis/resources/2.0.1.yml
> feat - Payments - 2.0.0-RC1.0

- swagger-apis/payments/2.0.0-rc1.0.yml
fix(Pagamentos): Ajustar link para openfinance
> fix(Pagamentos): Ajustar link para openfinance 

- dictionary/paymentsGetConsentsConsentId_v2.csv
- dictionary/paymentsGetPixPaymentsPaymentId_v2.csv
- dictionary/paymentsPatchPixPaymentsPaymentId_v2.csv
- dictionary/paymentsPostConsents_v2.csv
- dictionary/paymentsPostPixPayments_v2.csv
- swagger-apis/payments/2.0.0-rc1.0.yml
- swagger-apis/payments/2.0.0.yml
- swagger-apis/payments/index.html
**feat | fix (payments)**
- Ajustes no dicionario de dados;
- Atualização da versão
- Ajustes na descrição do campo payment/amount
> feat | fix (payments): Ajustes no dicionario de dados; Atualização da versão e Ajustes na descrição do campo payment/amount

- swagger-apis/accounts/2.0.1.yml
- swagger-apis/consents/2.0.1.yml
- swagger-apis/credit-cards/2.0.1.yml
**feat | fix(Accounts | Credit Cards | Consents):**
- Ajustar links na seção Orientações importantes;
- Corrigir referências na lista
> feat | fix(Accounts | Credit Cards | Consents): Ajustar links na seção Orientações importantes; Corrigir referências na lista

- swagger-apis/payments/2.0.0.yml
**feat - payments**
- Ajustar texto no header - Orientações
> feat(payments): SPB62 - Ajustar texto no header

- swagger-apis/capitalization-bonds/1.0.0-rc2.0.yml
- swagger-apis/capitalization-bonds/index.html
> GT-C - feat (Capitalização) -  Disponibilização da rc2.0 em PROD

- swagger-apis/pension/index.html
- Arquivo Index atualizado com a nova versão
> fix(Pension): Arquivo Index atualizado com a nova versão

- dictionary/variableIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdBrokerNotesBrokerNoteId_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentId_v1.csv
- dictionary/variableIncomesGetInvestments_v1.csv
- swagger-apis/variable-incomes/1.0.0-rc1.0.yml
- swagger-apis/variable-incomes/index.html
- PA 40: Alterar a obrigatoriedade do campo ”identificador da nota de negociação” dos endpoints movimentação e movimentação histórica;
- PA 45: Alteração nas especificações;
> GT-A - Feat(Variable Incomes): PA40, PA45

- dictionary/example/examples_treasureTitlesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/example/examples_treasureTitlesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/example/examples_treasureTitlesGetInvestmentsInvestmentIdTransactions_v1.csv
- dictionary/example/examples_treasureTitlesGetInvestmentsInvestmentId_v1.csv
- dictionary/example/examples_treasureTitlesGetInvestments_v1.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactions_v1.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentId_v1.csv
- dictionary/treasureTitlesGetInvestments_v1.csv
- swagger-apis/treasure-titles/1.0.0-rc1.0.yml
- swagger-apis/treasure-titles/index.html
- PA27: Criação da API de Tesouro Direto;
> GT-A - Dados do cliente - Feat(Treasure Titles) - PA 27

- swagger-apis/treasure-titles/1.0.0-rc1.0.yml
> GT-A - Dados do cliente - Feat(TreasureTitles): PA27 - Remover enum não utlizado

- dictionary/example/examples_fundsGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/example/examples_fundsGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/example/examples_fundsGetInvestmentsInvestmentIdTransactions_v1.csv
- dictionary/example/examples_fundsGetInvestmentsInvestmentId_v1.csv
- dictionary/example/examples_fundsGetInvestments_v1.csv
- dictionary/fundsGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/fundsGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/fundsGetInvestmentsInvestmentIdTransactions_v1.csv
- dictionary/fundsGetInvestmentsInvestmentId_v1.csv
- dictionary/fundsGetInvestments_v1.csv
- swagger-apis/funds/1.0.0-rc1.0.yml
- swagger-apis/funds/index.html
- PA32: Criação da API de Fundos de investimento;
- PA33: complementar as especificações de Investimentos;
> GT-A - Dados do cliente - Feat(Funds) PA32 e PA33: API de Fundos de investimento

- swagger-apis/insurances/1.0.0.yml
- swagger-apis/insurances/index.html
> GT - Dados abertos - feat(Insurances)

- swagger-apis/pension/1.0.0.yml
- swagger-apis/pension/index.html
> GT - Dados abertos - feat(Pension)

- dictionary/fundsGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/fundsGetInvestmentsInvestmentIdTransactions_v1.csv
- swagger-apis/funds/1.0.0-rc2.0.yml
- swagger-apis/funds/index.html
> GT Dados do cliente: Feat(Funds): v1.0.0-rc2.0

- swagger-apis/treasure-titles/1.0.0-rc2.0.yml
- swagger-apis/treasure-titles/index.html
> GT Dados do cliente: Feat(Treasure titles): v1.0.0-rc2.0 

- dictionary/variableIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdBrokerNotesBrokerNoteId_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
- swagger-apis/variable-incomes/1.0.0-rc2.0.yml
- swagger-apis/variable-incomes/index.html
> GT Dados do cliente: Feat(Variable incomes): v1.0.0-rc2.0 

- dictionary/banktFixedIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
- dictionary/banktFixedIncomesGetInvestmentsInvestmentId_v1.csv
- swagger-apis/bank-fixed-incomes/1.0.0-rc2.0.yml
- swagger-apis/bank-fixed-incomes/index.html
> GT Dados do cliente: Feat(Bank fixed incomes): v1.0.0-rc2.0 

- swagger-apis/webhook/1.0.0-beta.3.yml
- swagger-apis/webhook/index.html
> GT Serviço: feat(WebHook): v1.0.0-beta.3

- dictionary/consentsGetConsentsConsentId_v2.csv
- dictionary/consentsPostConsents_v2.csv
- swagger-apis/consents/2.1.0-rc2.0.yml
- swagger-apis/consents/index.html
Proposta contemplada nesse pull request
- PA80
> GT Dados do cliente: Fix(Consents): PA80 

- swagger-apis/webhook/1.0.0-rc.1.yml
- swagger-apis/webhook/index.html
> GT Serviço: feat(WebHook): 1.0.0-rc.1

- dictionary/paymentsGetConsentsConsentId_v3.csv
- dictionary/paymentsGetPixPaymentsPaymentId_v3.csv
- dictionary/paymentsPatchPixPaymentsPaymentId_v3.csv
- dictionary/paymentsPostConsents_v3.csv
- dictionary/paymentsPostPixPayments_v3.csv
- swagger-apis/payments/3.0.0-beta.1.yml
- swagger-apis/payments/index.html
> GT Serviços: feat(payments): versão 3.0.0-beta.1

- dictionary/capitalizationBondsGetProducts_v1.csv
- swagger-apis/capitalization-bonds/1.0.1.yml
- swagger-apis/capitalization-bonds/index.html
> Feat(Captalization-Bonds): PC85

- dictionary/getPersonalInsurance_v1.csv
- swagger-apis/insurances/1.0.1.yml
- swagger-apis/insurances/index.html
> GT - Dados abertos - feat(Insurances): PC106 e PC107

- dictionary/getPensionRiskCoverages_v1.csv
- dictionary/getPensionSurvivalCoverages_v1.csv
- swagger-apis/pension/1.0.1.yml
- swagger-apis/pension/index.html
> GT - Dados abertos - feat(Pension) PC105

- dictionary/paymentsGetConsentsConsentId_v3.csv
- dictionary/paymentsGetPixPaymentsPaymentId_v3.csv
- dictionary/paymentsPatchPixPaymentsPaymentId_v3.csv
- dictionary/paymentsPostConsents_v3.csv
- dictionary/paymentsPostPixPayments_v3.csv
- swagger-apis/payments/3.0.0-beta.2.yml
- swagger-apis/payments/index.html
> GT Serviços: feat(payments): Versão 3.0.0-beta.2

- dictionary/creditFixedIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
- dictionary/creditFixedIncomesGetInvestmentsInvestmentId_v1.csv
- swagger-apis/credit-fixed-incomes/1.0.0-rc3.0.yml
- swagger-apis/credit-fixed-incomes/index.html
> GT Serviços: Feat(Credit Fixed Incomes) Nova versão: 1.0.0-rc3.0

- dictionary/banktFixedIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
- swagger-apis/bank-fixed-incomes/1.0.0-rc3.0.yml
- swagger-apis/bank-fixed-incomes/index.html
> GT Serviços: Feat(Bank Fixed Incomes) Nova versão: 1.0.0-rc3.0

- swagger-apis/webhook/1.0.0-rc.2.yml
- swagger-apis/webhook/index.html
> GT Serviço: Feat(Webhook): Versão: 1.0.0-rc.2

- swagger-apis/webhook/1.0.0.yml
- swagger-apis/webhook/index.html
> GT Serviço: Feat(Webhook): Versão: 1.0.0

- dictionary/treasureTitlesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactions_v1.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentId_v1.csv
- swagger-apis/treasure-titles/1.0.0.yml
- swagger-apis/treasure-titles/index.html
> GT Dados do cliente: Feat(Treasure titles): Versão 1.0.0

- dictionary/fundsGetInvestmentsInvestmentIdBalances_v1.csv
- swagger-apis/funds/1.0.0.yml
- swagger-apis/funds/index.html
> GT Dados do cliente: Feat(Funds): Versão 1.0.0

- dictionary/variableIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdBrokerNotesBrokerNoteId_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
- swagger-apis/variable-incomes/1.0.0.yml
- swagger-apis/variable-incomes/index.html
> GT Dados do cliente: Feat(Variable Incomes): Versão 1.0.0

- dictionary/creditFixedIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
- swagger-apis/credit-fixed-incomes/1.0.0.yml
- swagger-apis/credit-fixed-incomes/index.html
> GT Dados do Cliente: Feat(Credit Fixed Incomes): Versão 1.0.0

- swagger-apis/consents/2.1.0.yml
- swagger-apis/consents/index.html
> GT Dados do Cliente: Feat(Consents): Versão 2.1.0

- dictionary/getOutage_v2.csv
- dictionary/getStatus_v2.csv
- swagger-apis/common/2.0.0-beta.1.yml
- swagger-apis/common/index.html
> GT Dados abertos: Feat(common): Versão 2.0.0-beta.1

- dictionary/accountsGetAccountsAccountIdBalances_v2.csv
- dictionary/accountsGetAccountsAccountIdOverdraftLimits_v2.csv
- dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
- dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
- dictionary/accountsGetAccountsAccountId_v2.csv
- dictionary/accountsGetAccounts_v2.csv
- swagger-apis/accounts/2.1.0-rc.1.yml
- swagger-apis/accounts/index.html
> GT Dados do cliente: Feat(Accounts): Versão 2.1.0-rc.1

- dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.csv
- dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.csv
- dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.csv
- dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.csv
- dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.csv
- dictionary/creditCardsGetAccountsCreditCardAccountId_v2.csv
- dictionary/creditCardsGetAccounts_v2.csv
- swagger-apis/credit-cards/2.1.0-rc.1.yml
- swagger-apis/credit-cards/index.html
> GT Dados do Cliente: Feat(Credit card): versão 2.1.0-rc.1

- dictionary/loansGetContractsContractIdPayments_v2.csv
- dictionary/loansGetContractsContractIdScheduledInstalments_v2.csv
- dictionary/loansGetContractsContractIdWarranties_v2.csv
- dictionary/loansGetContractsContractId_v2.csv
- dictionary/loansGetContracts_v2.csv
- swagger-apis/loans/2.1.0-rc.1.yml
- swagger-apis/loans/index.html
> GT dados do cliente: Feat(Loans): versão 2.1.0-rc.1

- dictionary/financingsGetContractsContractIdPayments_v2.csv
- dictionary/financingsGetContractsContractIdScheduledInstalments_v2.csv
- dictionary/financingsGetContractsContractIdWarranties_v2.csv
- dictionary/financingsGetContractsContractId_v2.csv
- dictionary/financingsGetContracts_v2.csv
- swagger-apis/financings/2.1.0-rc.1.yml
- swagger-apis/financings/index.html
> GT dados do cliente: Feat(financings): Versão 2.1.0-rc.1.yml

- dictionary/unarrangedAccountsOverdraftGetContractsContractIdPayments_v2.csv
- dictionary/unarrangedAccountsOverdraftGetContractsContractIdScheduledInstalments_v2.csv
- dictionary/unarrangedAccountsOverdraftGetContractsContractIdWarranties_v2.csv
- dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.csv
- dictionary/unarrangedAccountsOverdraftGetContracts_v2.csv
- swagger-apis/unarranged-accounts-overdraft/2.1.0-rc.1.yml
- swagger-apis/unarranged-accounts-overdraft/index.html
> GT Dados do Cliente: Feat(Unarrange Accounts): versão  2.1.0-rc.1.yml

- dictionary/invoiceFinancingsGetContractsContractIdPayments_v2.csv
- dictionary/invoiceFinancingsGetContractsContractIdScheduledInstalments_v2.csv
- dictionary/invoiceFinancingsGetContractsContractIdWarranties_v2.csv
- dictionary/invoiceFinancingsGetContractsContractId_v2.csv
- dictionary/invoiceFinancingsGetContracts_v2.csv
- swagger-apis/invoice-financings/2.1.0-rc.1.yml
- swagger-apis/invoice-financings/index.html
> GT Dados do Cliente. Feat(Invoice Financings): Versão 2.1.0-rc.1.yml

- dictionary/getEnrollment_v1.csv
- dictionary/postEnrollments_v1.csv
- swagger-apis/enrollments/1.0.0-rc.1.yml
- swagger-apis/enrollments/index.html
> Squad sem redirecionamento: Feat(Enrollments): Versão 1.0.0-rc.1

- dictionary/getEnrollment_v1.csv
- dictionary/postEnrollments_v1.csv
- swagger-apis/enrollments/1.0.0-rc.1.yml
- swagger-apis/enrollments/index.html
> Squad sem Redirecionamento Fear(Enrollments): Versão 1.0.0-rc.1

- dictionary/getEnrollment_v1.csv
- swagger-apis/enrollments/1.0.0-rc.1.yml
> Squad Sem redirecionamento: FIX(Enrollments): Versão 1.0.0-rc.1

- dictionary/paymentsGetConsentsConsentId_v3.csv
- swagger-apis/payments/3.0.0-beta.3.yml
- swagger-apis/payments/index.html
> GT Serviços: feat(Payments): Versão 3.0.0-beta.3

- swagger-apis/webhook/1.1.0.yml
- swagger-apis/webhook/index.html
> GT Serviços: Feat(Webhook): Versão 1.1.0

- swagger-apis/treasure-titles/1.0.1.yml
- swagger-apis/treasure-titles/index.html
> GT Dados do cliente: Feat(Treasure titles): Versão 1.0.1

- swagger-apis/funds/1.0.1.yml
- swagger-apis/funds/index.html
> GT Dados do cliente: Feat(Funds): Versão 1.0.1

- dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.csv
- dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.csv
- dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.csv
- swagger-apis/credit-cards/2.1.0-rc.2.yml
- swagger-apis/credit-cards/index.html
> GT Dados do cliente: Feat(Credit cards): Versão 2.1.0-rc.2

- dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
- dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
- swagger-apis/accounts/2.1.0-rc.2.yml
- swagger-apis/accounts/index.html
> GT Dados do cliente: Feat(Accounts): Versão 2.1.0-rc.2

- dictionary/paymentsPostPixPayments_v2.csv
- dictionary/paymentsPostPixPayments_v3.csv
- swagger-apis/payments/2.1.0.yml
- swagger-apis/payments/3.1.0.yml
- swagger-apis/payments/index.html
**Versão 2.1.0 e Versão 3.1.0**
> GT Serviços: Feat(Payments): Versão 2.1.0 e Versão 3.1.0

- dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
- dictionary/enrollmentCreateFidoSigningOptions_v1.csv
- dictionary/enrollmentRegisterFidoCredential_v1.csv
- swagger-apis/enrollments/1.0.0-rc.2.yml
- swagger-apis/enrollments/index.html
> GT Serviços: Feat(Enrollments): Versão 1.0.0-rc.2.yml

- swagger-apis/enrollments/1.0.0-rc.3.yml
Durante as reuniões dos dias 25/08 e 29/08 da Squad Jornada Sem Redirecionamento, foi conduzida pelo grupo uma revisão dos endpoints, tal revisão resultou em diversas alterações que agora encontram-se nesse PR. 
Endpoints já revisados:
POST /enrollments
GET /enrollments/{enrollmentId}
PATCH /enrollments/{enrollmentId}
Importante observar que algumas das alterações feitas durante a revisão alterarão componentes reutilizados em outros endpoints não supracitados.
> 1.0.0-rc.3.yml - Revisões de endpoints feitas na Squad

- swagger-apis/enrollments/index.html
Adicionando versão 1.0.0-rc.3 no arquivo index.html
> GT Serviços: Feat(Enrollments): Adicionando versão 1.0.0-rc.3 no arquivo index.html

- dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
- dictionary/enrollmentCreateFidoSigningOptions_v1.csv
Adicionando dicionario de dados; Versão 1.0.0-rc.3
> GT Serviços; Feat(Enrollments): Adicionando dicionario de dados

- swagger-apis/enrollments/1.1.0.yml
- swagger-apis/enrollments/index.html
- Adicionando versão  Versão 1.1.0
> GT Serviços; Feat(Enrollments): Versão 1.1.0

- dictionary/consentsGetConsentsConsentIdExtends_v2.csv
- dictionary/consentsGetConsentsConsentId_v2.csv
- dictionary/consentsPostConsentsConsentIdExtends_v2.csv
- swagger-apis/consents/2.2.0.yml
- swagger-apis/consents/index.html
> GT Dados do cliente: feat(Consents): Versão 2.2.0

- swagger-apis/consents/2.2.0-beta.1.yml
- swagger-apis/consents/2.2.0.yml
- swagger-apis/consents/index.html
> GT Dados do cliente: fix(Consents): Versão 2.2.0-beta.1 

- swagger-apis/consents/2.2.0-beta.1.yml
Ajustando details de enum status code 422
> GT Dados do cliente: fix(consents): Ajustando details de enum status code 422

- dictionary/paymentsGetConsentsConsentId_v3.0.0.csv
- dictionary/paymentsGetPixPaymentsPaymentId_v3.0.0.csv
- dictionary/paymentsPatchPixPaymentsPaymentId_v3.0.0.csv
- dictionary/paymentsPostConsents_v3.0.0.csv
- dictionary/paymentsPostPixPayments_v3.0.0.csv
- swagger-apis/payments/3.0.0.yml
- swagger-apis/payments/index.html
> GT Serviços: Feat(Payments): Versão 3.0.0

- dictionary/getBusinessAccounts_v1.csv
- dictionary/getPersonalAccounts_v1.csv
- swagger-apis/opendata-accounts/1.0.0-beta.1.yml
- swagger-apis/opendata-accounts/index.html
> GT Dados Abertos: Feat(Open Data Accounts): Versão 1.0.0-Beta 1

- dictionary/getBusinessUnarrangedAccountOverdraft_v1.csv
- dictionary/getPersonalUnarrangedAccountOverdraft_v1.csv
- swagger-apis/opendata-unarranged/1.0.0-beta.1.yml
- swagger-apis/opendata-unarranged/index.html
> GT Dados Abertos: Feat(Open Data Unarranged Account Overdraft): Versão 1.0.0-Beta 1

- dictionary/getBusinessFinancings_v1.csv
- dictionary/getPersonalFinancings_v1.csv
- swagger-apis/opendata-financings/1.0.0-beta.1.yml
- swagger-apis/opendata-financings/index.html
> GT Dados Abertos: Feat(OpenData Financings): Versão 1.0.0-beta.1

- dictionary/getBusinessCreditCards_v1.csv
- dictionary/getPersonalCreditCards_v1.csv
- swagger-apis/opendata-creditcards/1.0.0-beta.1.yml
- swagger-apis/opendata-creditcards/index.html
> GT Dados Abertos: Feat(OpenData Credit Cards): Versão 1.0.0-beta.1

- dictionary/getPersonalInvoiceFinancings_v1.csv
- swagger-apis/opendata-invoicefinancings/1.0.0-beta.1.yml
- swagger-apis/opendata-invoicefinancings/index.html
> GT Dados Abertos: Feat(Invoice): Versão 1.0.0-beta.1

- dictionary/getBusinessLoans_v1.csv
- dictionary/getPersonalLoans_v1.csv
- swagger-apis/opendata-loans/1.0.0-beta.1.yml
- swagger-apis/opendata-loans/index.html
> GT Dados Abertos: Feat(OpenData Credit Loans): Versão 1.0.0-beta.1

- dictionary/paymentsPostPixPayments_v3.0.0.csv
- dictionary/paymentsPostPixPayments_v3.csv
- swagger-apis/payments/3.0.0.yml
> GT Serviços: Feat(Payment): PSV103

- dictionary/getBusinessLoans_v1.csv
- dictionary/getPersonalLoans_v1.csv
- swagger-apis/opendata-loans/1.0.0-beta.1.yml
> GT Dados abertos: Feat(Opendata Loans): PC143

- dictionary/getBusinessFinancings_v1.csv
- dictionary/getPersonalFinancings_v1.csv
- swagger-apis/opendata-financings/1.0.0-beta.1.yml
> GT Dados abertos: Feat(Opendata Financings): PC143

- dictionary/getBusinessInvoiceFinancings_v1.csv
- dictionary/getPersonalInvoiceFinancings_v1.csv
- swagger-apis/opendata-invoicefinancings/1.0.0-beta.1.yml
> GT Dados abertos: Feat(Opendata Invoice Financings): PC143

- swagger-apis/funds/1.0.2.yml
- swagger-apis/funds/index.html
> GT Dados do Cliente: Feat(Funds): Adicionando versão 1.0.2

- swagger-apis/variable-incomes/1.0.2.yml
- swagger-apis/variable-incomes/index.html
> GT Dados do Cliente: Feat(Variable Incomes): Adicionando versão 1.0.2

- swagger-apis/bank-fixed-incomes/1.0.2.yml
- swagger-apis/bank-fixed-incomes/index.html
> GT Dados do Cliente: Feat(Bank Fixed Incomes): Adicionando versão 1.0.2

- dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
- dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
- swagger-apis/accounts/2.1.0-rc.3.yml
- swagger-apis/accounts/index.html
> GT Dados do Cliente: Feat(accounts): PDC187

- dictionary/financingsGetContractsContractIdWarranties_v2.csv
- dictionary/financingsGetContractsContractId_v2.csv
- swagger-apis/financings/2.1.0-rc.2.yml
- swagger-apis/financings/index.html
> GT dados do cliente: feat(Financings): Nova Versão 2.1.0-rc.2

- dictionary/unarrangedAccountsOverdraftGetContractsContractIdWarranties_v2.csv
- swagger-apis/unarranged-accounts-overdraft/2.1.0-rc.2.yml
- swagger-apis/unarranged-accounts-overdraft/index.html
> GT Dados do Cliente: Feat(Unarranged Accounts) PDC232, PDC234

- swagger-apis/consents/2.2.0-rc.1.yml
- swagger-apis/consents/index.html
> GT Dados do Cliente: Feat(Consents): Versão 2.2.0-rc.1

- dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsPostRecurringConsents_v1.csv
- swagger-apis/automatic-payments/1.0.0-beta.1.yml
- swagger-apis/automatic-payments/index.html
> GT Serviços: Feat(Automatic Payments): Versão 1.0.0

- swagger-apis/admin/2.0.0.yml
- swagger-apis/admin/index.html
> GT Dados abertos: Feat(Admins): Versão: 2.0.0

- swagger-apis/credit-cards/2.1.0.yml
- swagger-apis/credit-cards/index.html
> GT Dados do Cliente: Feat(Credit card): versão 2.1.0

- swagger-apis/accounts/2.1.0.yml
- swagger-apis/accounts/index.html
> GT Dados do cliente: Feat(Accounts): Versão 2.1.0

- dictionary/unarrangedAccountsOverdraftGetContractsContractIdWarranties_v2.csv
- swagger-apis/unarranged-accounts-overdraft/2.1.0.yml
- swagger-apis/unarranged-accounts-overdraft/index.html
> GT Dados do Cliente: Feat(Unarranged Account Overdraft): Versão 2.1.0

- dictionary/invoiceFinancingsGetContractsContractIdWarranties_v2.csv
- swagger-apis/invoice-financings/2.1.0.yml
- swagger-apis/invoice-financings/index.html
> GT dados do cliente: Feat(Invoice Financings): Versão 2.1.0

- dictionary/financingsGetContractsContractIdWarranties_v2.csv
- swagger-apis/financings/2.1.0.yml
- swagger-apis/financings/index.html
> GT dados do cliente: Feat(financings): Versão 2.1.0

- dictionary/loansGetContractsContractIdWarranties_v2.csv
- swagger-apis/loans/2.1.0.yml
- swagger-apis/loans/index.html
> GT Dados do cliente: Feat(Loans) Versão 2.1.0

- dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
- dictionary/enrollmentCreateFidoSigningOptions_v1.csv
- swagger-apis/enrollments/1.2.0.yml
- swagger-apis/enrollments/index.html
**Feat(Enrollments) versão 1.2.0**
> GT Serviços: Feat(Enrollments) versão 1.2.0

- dictionary/paymentsGetConsentsConsentId_v4.csv
- dictionary/paymentsGetPixPaymentsPaymentId_v4.csv
- dictionary/paymentsPatchPixPaymentsConsentId_v4.csv
- dictionary/paymentsPatchPixPaymentsPaymentId_v4.csv
- dictionary/paymentsPostConsents_v4.csv
- dictionary/paymentsPostPixPayments_v4.csv
- swagger-apis/payments/4.0.0-beta.2.yml
- swagger-apis/payments/index.html
> GT Serviços: Feat(Payments): Versão 4.0.0-beta.2

- dictionary/getMetrics_v2.csv
- swagger-apis/admin/2.0.0.yml
> GT Dados abertos: Feat(admin) : PDA226

- dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPostRecurringConsents_v1.csv
- swagger-apis/automatic-payments/1.0.0-beta.2.yml
- swagger-apis/automatic-payments/index.html
> GT Serviços: Feat(Automatic Payments): Versão 1.0.0-beta.2

- dictionary/resourcesGetResources_v3.csv
- swagger-apis/resources/3.0.0-beta.1.yml
- swagger-apis/resources/index.html
> GT Dados do cliente; Feat(Resources): Versão 3.0.0-beta.1

- swagger-apis/exchanges/1.0.0-rc2.0.yml
- swagger-apis/exchanges/index.html
> GT Dados do cliente: Feat(Exchanges): Versão 1.0.0-rc2.0

- dictionary/consentsDeleteConsentsConsentId_v3.csv
- dictionary/consentsGetConsentsConsentIdExtensions_v3.csv
- dictionary/consentsGetConsentsConsentId_v3.csv
- swagger-apis/consents/3.0.0-beta.1.yml
- swagger-apis/consents/index.html
> GT dados do Cliente: Feat(Consents): Versão 3.0.0-beta.1

- dictionary/getBusinessFinancings_v1.csv
- dictionary/getPersonalFinancings_v1.csv
- swagger-apis/opendata-financings/1.0.0-beta.2.yml
- swagger-apis/opendata-financings/index.html
> GT Dados abertos: Feat(opendata Financings): Versão 1.0.0-beta.2

- dictionary/getBusinessUnarrangedAccountOverdraft_v1.csv
- dictionary/getPersonalUnarrangedAccountOverdraft_v1.csv
- swagger-apis/opendata-unarranged/1.0.0-beta.2.yml
- swagger-apis/opendata-unarranged/index.html
> GT Dados abertos: Feat(opendata Unarranged): Versão 1.0.0-beta.2

- dictionary/getBusinessLoans_v1.csv
- dictionary/getPersonalLoans_v1.csv
- swagger-apis/opendata-loans/1.0.0-beta.2.yml
- swagger-apis/opendata-loans/index.html
> GT Dados abertos: Feat(opendata Loans): Versão 1.0.0-beta.2

- dictionary/getBusinessInvoiceFinancings_v1.csv
- dictionary/getPersonalInvoiceFinancings_v1.csv
- swagger-apis/opendata-invoicefinancings/1.0.0-beta.2.yml
- swagger-apis/opendata-invoicefinancings/index.html
> GT Dados abertos: Feat(opendata Invoice Financings): Versão 1.0.0-beta.2

- dictionary/getBusinessCreditCards_v1.csv
- dictionary/getPersonalCreditCards_v1.csv
- swagger-apis/opendata-creditcards/1.0.0-beta.2.yml
- swagger-apis/opendata-creditcards/index.html
> GT Dados abertos: Feat(opendata Credit Cards): Versão 1.0.0-beta.2

- dictionary/getBusinessAccounts_v1.csv
- dictionary/getPersonalAccounts_v1.csv
- swagger-apis/opendata-accounts/1.0.0-beta.2.yml
- swagger-apis/opendata-accounts/index.html
> GT Dados abertos: Feat(opendata Accounts): Versão 1.0.0-beta.2

- dictionary/getBankingAgents_v2.csv
- dictionary/getBranches_v2.csv
- dictionary/getElectronicChannels_v2.csv
- dictionary/getPhoneChannels_v2.csv
- dictionary/getSharedAutomatedTellerMachines_v2.csv
- swagger-apis/channels/2.0.0-beta.1.yml
- swagger-apis/channels/index.html
> GT Dados abertos: Feat(Channels): Versão 2.0.0-beta.1

- dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsPostRecurringConsents_v1.csv
- swagger-apis/automatic-payments/1.0.0-beta.3.yml
- swagger-apis/automatic-payments/index.html
> GT Serviços: Feat(Automatic Payments): Versão 1.0.0-beta.3

- dictionary/paymentsGetConsentsConsentId_v4.csv
- dictionary/paymentsPostConsents_v4.csv
- swagger-apis/payments/4.0.0-beta.3.yml
- swagger-apis/payments/index.html
> GT Serviços: Feat(Payments): Versão 4.0.0-beta.3

- swagger-apis/accounts/2.1.1.yml
- swagger-apis/accounts/index.html
> GT Dados do Cliente: Feat(Accounts): Versão: 2.1.1

- dictionary/exchangesGetOperationsOperationIdEvents_v1.csv
- dictionary/exchangesGetOperationsOperationId_v1.csv
- swagger-apis/exchanges/1.0.0-rc.3.yml
- swagger-apis/exchanges/index.html
> GT Dados do cliente: Feat(Exchanges): Versão 1.0.0-rc.3

- dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsPostRecurringConsents_v1.csv
- swagger-apis/automatic-payments/1.0.0-beta.5.yml
> GT Serviços: feat(Automatic-payments) - Versão 1.0.0-beta.5

- dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsPostRecurringConsents_v1.csv
- swagger-apis/automatic-payments/1.0.0-beta.5.yml
- swagger-apis/automatic-payments/index.html
> GT Serviços: Feat(automatic-payments): versão 1.0.0-beta.5

- swagger-apis/consents/3.0.0-beta.2.yml
- swagger-apis/consents/index.html
> GT Dados do cliente: Feat(Consents): Versão 3.0.0-beta.2

- dictionary/getOutage_v2.csv
- dictionary/getStatus_v2.csv
- swagger-apis/common/2.0.0-beta.2.yml
- swagger-apis/common/index.html
> GT - Dados abertos: Feat(Common): Versão 2.0.0-beta.2

- swagger-apis/resources/3.0.0-beta.2.yml
- swagger-apis/resources/index.html
> GT Dados do cliente: Feat(Resources): Versão 3.0.0-beta.2

- dictionary/variableIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/variableIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
- swagger-apis/variable-incomes/1.1.0.yml
- swagger-apis/variable-incomes/index.html
> GT Dados do Cliente: Feat(Variable Incomes): Versão 1.1.0

- dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
- dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
- swagger-apis/accounts/2.2.0.yml
- swagger-apis/accounts/index.html
> GT Dados do Cliente: Feat(Accounts): Versão: 2.2.0

- dictionary/exchangesGetOperationsOperationIdEvents_v1.csv
- dictionary/exchangesGetOperationsOperationId_v1.csv
- swagger-apis/exchanges/1.0.0-rc.4.yml
- swagger-apis/exchanges/index.html
> GT Dados do cliente - feat(exchanges) versão 1.0.0-rc.4

- dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
- swagger-apis/automatic-payments/1.0.0-rc.1.yml
- swagger-apis/automatic-payments/index.html
> GT Serviços: Feat(Automatic Payments): Versão: v1.0.0-rc.1

- dictionary/consentsGetConsentsConsentId_v3.csv
- swagger-apis/consents/3.0.0-beta.3.yml
- swagger-apis/consents/index.html
> GT Dados do cliente:  Feat(Consents): Versão v3.0.0-beta.3

- swagger-apis/resources/3.0.0-beta.3.yml
- swagger-apis/resources/index.html
> GT Dados do Cliente: Feat(Resources) versão 3.0.0-beta.3

- swagger-apis/opendata-accounts/1.0.0-rc.1.yml
- swagger-apis/opendata-accounts/index.html
> GT Dados Abertos: Feat(OpenData-Account): v1.0.0-rc.1

- swagger-apis/automatic-payments/index.html
Adicionando versão **1.0.0-beta.5** no arquivo index da api de automatic-payments.
> GT Serviços: Fix(automatic-payments): Ajustando arquivo index - versão 1.0.0-beta.5

- swagger-apis/consents/3.0.0-rc.1.yml
- swagger-apis/consents/index.html
> GT Dados do cliente: Feat(consents) - Versão 3.0.0-rc.1

- swagger-apis/resources/3.0.0-rc.1.yml
- swagger-apis/resources/index.html
> GT Dados do cliente: Feat(Resources): 3.0.0-rc.1

- swagger-apis/common/2.0.0.yml
- swagger-apis/common/index.html
> GT Dados Abertos | Comum / OpenData Common | Versão 2.0.0

- swagger-apis/opendata-creditcards/1.0.0.yml
- swagger-apis/opendata-creditcards/index.html
> GT Dados Abertos | Cartões de Crédito / OpenData Credit Cards | Versão 1.0.0

- swagger-apis/opendata-accounts/1.0.0.yml
- swagger-apis/opendata-accounts/index.html
> GT Dados Abertos | Contas / OpenData Accounts | Versão 1.0.0

- dictionary/getBusinessLoans_v1.csv
- dictionary/getPersonalLoans_v1.csv
- swagger-apis/opendata-loans/1.0.0.yml
- swagger-apis/opendata-loans/index.html
> GT Dados Abertos | Empréstimos / OpenData Loans| Versão 1.0.0

- dictionary/getBusinessFinancings_v1.csv
- dictionary/getPersonalFinancings_v1.csv
- swagger-apis/opendata-financings/1.0.0.yml
- swagger-apis/opendata-financings/index.html
> GT Dados Abertos | Financiamentos/ OpenData Financings | Versão 1.0.0

- dictionary/getBusinessInvoiceFinancings_v1.csv
- dictionary/getPersonalInvoiceFinancings_v1.csv
- swagger-apis/opendata-invoicefinancings/1.0.0.yml
- swagger-apis/opendata-invoicefinancings/index.html
> GT Dados Abertos | Direitos Creditórios Descontados / OpenData Invoice Financings | Versão 1.0.0 

- dictionary/getBusinessUnarrangedAccountOverdraft_v1.csv
- dictionary/getPersonalUnarrangedAccountOverdraft_v1.csv
- swagger-apis/opendata-unarranged/1.0.0.yml
- swagger-apis/opendata-unarranged/index.html
> GT Dados Abertos | Adiantamento a Depositantes / OpenData Unarranged Account Overdraft | Versão 1.0.0

- swagger-apis/channels/2.0.0.yml
- swagger-apis/channels/index.html
> GT Dados Abertos | Canais de atendimento / OpenData Channels | Versão 2.0.0

- dictionary/paymentsGetConsentsConsentId_v4.csv
- dictionary/paymentsPostConsents_v4.csv
- swagger-apis/payments/4.0.0-rc.2.yml
- swagger-apis/payments/index.html
> GT Serviços: Feat(Payments) Versão v4.0.0-rc.2

- swagger-apis/credit-cards/index.html
> GT Dados do Cliente: Feat(Credit card): Versão 2.2.1

- dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
- dictionary/automaticPaymentsPostRecurringConsents_v1.csv
- swagger-apis/automatic-payments/1.0.0-rc.3.yml
- swagger-apis/automatic-payments/index.html
- swagger-apis/credit-cards/index.html
> GT Serviços: Feat(Automatic-payments): Versão 1.0.0-rc.3

- dictionary/getPensionRiskCoverages_v2.csv
- dictionary/getPensionSurvivalCoverages_v2.csv
- swagger-apis/pension/2.0.0-beta.1.yml
- swagger-apis/pension/index.html
> GT - Dados abertos - feat(Pension) Versão 2.0.0-beta.1

- dictionary/capitalizationBondsGetProducts_v2.csv
- swagger-apis/capitalization-bonds/2.0.0-beta.1.yml
- swagger-apis/capitalization-bonds/index.html
> GT Dados Abertos: Feat(Captalization Bonds): Versão 2.0.0-beta.1

- dictionary/exchangesGetOperationsOperationIdEvents_v1.csv
- dictionary/exchangesGetOperationsOperationId_v1.csv
- swagger-apis/exchanges/1.0.0-rc.6.yml
- swagger-apis/exchanges/index.html
> GT Dados do cliente - feat(exchanges) versão 1.0.0-rc.6

- dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
- dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
- dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
- swagger-apis/automatic-payments/1.0.0.yml
- swagger-apis/automatic-payments/index.html
> GT Serviços: Feat(Automatic-payments): Versão 1.0.0

- swagger-apis/resources/3.0.0.yml
- swagger-apis/resources/index.html
> GT Dados do Cliente: Feat(Resources) Versão 3.0.0

- swagger-apis/consents/3.0.0.yml
- swagger-apis/consents/index.html
> GT Dados do Cliente: Feat(Consents) Versão 3.0.0

- swagger-apis/payments/4.0.0.yml
- swagger-apis/payments/index.html
> GT Serviços: Feat(Payments): Versão 4.0.0

- dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
- dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
- swagger-apis/accounts/2.2.1.yml
- swagger-apis/accounts/index.html
> GT Dados do Cliente: Feat(Accounts): Versão: 2.2.1

- dictionary/getPersonalInsurance_v2.csv
- swagger-apis/insurances/2.0.0-beta.1.yml
- swagger-apis/insurances/index.html
> GT - Dados abertos - feat(Insurances): Versão 2.0.0-beta.1

- dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
- dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
- swagger-apis/credit-fixed-incomes/1.0.2.yml
- swagger-apis/credit-fixed-incomes/index.html
> GT Dados do Cliente: Feat(Credit Fixed Incomes): Adicionando versão 1.0.2

- dictionary/getPersonalInsurance_v2.csv
- swagger-apis/insurances/2.0.0-beta.2.yml
- swagger-apis/insurances/index.html
> GT - Dados abertos - feat(Insurances): Versão 2.0.0-beta.2

- dictionary/capitalizationBondsGetProducts_v2.csv
- swagger-apis/capitalization-bonds/2.0.0-beta.2.yml
- swagger-apis/capitalization-bonds/index.html
> GT - Dados abertos - feat(Capitalization-bonds): Versão 2.0.0-beta.2

- dictionary/getPensionRiskCoverages_v2.csv
- dictionary/getPensionSurvivalCoverages_v2.csv
- swagger-apis/pension/2.0.0-beta.2.yml
- swagger-apis/pension/index.html
> GT - Dados abertos - feat(Pension): Versão 2.0.0-beta.2

- dictionary/capitalizationBondsGetProducts_v2.csv
- swagger-apis/capitalization-bonds/2.0.0-rc.1.yml
- swagger-apis/capitalization-bonds/index.html
> GT Dados Abertos: Feat(Captalization Bonds): Versão 2.0.0-rc.1

- dictionary/getPensionRiskCoverages_v2.csv
- swagger-apis/pension/2.0.0-rc.1.yml
- swagger-apis/pension/index.html
> GT - Dados abertos - feat(Pension): Versão 2.0.0-rc.1

- swagger-apis/insurances/2.0.0-rc.1.yml
- swagger-apis/insurances/index.html
> GT - Dados abertos - feat(Insuranse): Versão 2.0.0-rc.1

- dictionary/loansGetContractsContractId_v2.csv
- dictionary/loansGetContracts_v2.csv
- swagger-apis/loans/2.2.0.yml
- swagger-apis/loans/index.html
> GT Dados do cliente: Feat(Loans) Versão 2.2.0

- swagger-apis/accounts/2.4.0-beta.1.yml
- swagger-apis/accounts/index.html
> GT Dados do cliente: Feat(Accounts) Versão 2.4.0-beta.1

- dictionary/customersGetBusinessFinancialRelations_v2.csv
- dictionary/customersGetBusinessIdentifications_v2.csv
- dictionary/customersGetBusinessQualifications_v2.csv
- dictionary/customersGetPersonalFinancialRelations_v2.csv
- dictionary/customersGetPersonalIdentifications_v2.csv
- dictionary/customersGetPersonalQualifications_v2.csv
- swagger-apis/customers/2.2.0.yml
- swagger-apis/customers/index.html
> GT Dados do cliente: Feat(Customers) Versão 2.2.0

- dictionary/getPensionRiskCoverages_v2.csv
- dictionary/getPensionSurvivalCoverages_v2.csv
- swagger-apis/pension/2.0.0.yml
- swagger-apis/pension/index.html
> GT - Dados abertos - feat(Pension): Versão 2.0.0

- dictionary/getPersonalInsurance_v2.csv
- swagger-apis/insurances/2.0.0.yml
- swagger-apis/insurances/index.html
> GT - Dados abertos - feat(Insurances): Versão 2.0.0

- dictionary/getMetrics_v2 copy.csv
- swagger-apis/admin/2.0.1.yml
- swagger-apis/admin/index.html
> GT Dados abertos: Feat(Admins): Versão 2.0.1

- swagger-apis/common/2.0.1.yml
- swagger-apis/common/index.html
> GT Dados Abertos (Common) Versão 2.0.1

- swagger-apis/accounts/2.4.0-beta.2.yml
- swagger-apis/accounts/index.html
> GT Dados do cliente: Feat(Accounts) Versão 2.4.0-beta.2

- swagger-apis/customers/2.1.0-beta.3.yml
- swagger-apis/customers/index.html
> GT Dados do cliente: Feat(Customers) Versão 2.1.0-beta.3

- swagger-apis/accounts/2.4.0-rc.1.yml
- swagger-apis/accounts/index.html
> GT Dados do cliente: Feat(Accounts) Versão 2.4.0-rc.1

- swagger-apis/customers/2.1.0-rc.1.yml
- swagger-apis/customers/index.html
> GT Dados do cliente: Feat(Customers) Versão 2.1.0-rc.1

- dictionary/customersGetBusinessIdentifications_v2.csv
- dictionary/customersGetPersonalFinancialRelations_v2.csv
- dictionary/customersGetPersonalIdentifications_v2.csv
- swagger-apis/customers/2.1.0-rc.2.yml
- swagger-apis/customers/index.html
> GT dados do Cliente: Feat(Customers): Lançamento versão 2.1.0-rc.2

- dictionary/variableIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- swagger-apis/variable-incomes/1.2.0.yml
- swagger-apis/variable-incomes/index.html
> GT Dados do cliente: Feat(Variable incomes) Lançamento versão 1.2.0

- swagger-apis/enrollments/2.0.0-beta.1.yml
- swagger-apis/enrollments/index.html
> GT Serviços: Feat(Enrollments) Versão 2.0.0-beta.1

- swagger-apis/customers/2.1.0.yml
- swagger-apis/customers/index.html
> GT Dados do cliente: Feat(Customers) Versão 2.1.0

- swagger-apis/consents/3.0.1.yml
- swagger-apis/consents/index.html
> GT Dados do Cliente: Feat(Consents) Versão 3.0.1

- swagger-apis/opendata-financings/1.0.1.yml
- swagger-apis/opendata-financings/index.html
> GT Dados abertos: Feat(open data Financings): Versão 1.0.1

- swagger-apis/opendata-accounts/1.0.1.yml
- swagger-apis/opendata-accounts/index.html
> GT Dados abertos: Feat(open data Accounts): Versão 1.0.1

- swagger-apis/opendata-unarranged/1.0.1.yml
- swagger-apis/opendata-unarranged/index.html
> GT Dados abertos: Feat(open data Unarranged): Versão 1.0.1

- swagger-apis/opendata-creditcards/1.0.1.yml
- swagger-apis/opendata-creditcards/index.html
> GT Dados abertos: Feat(open data Credit Card): Versão 1.0.1

- swagger-apis/opendata-loans/1.0.1.yml
- swagger-apis/opendata-loans/index.html
> GT Dados abertos: Feat(open data Loans): Versão 1.0.1

- swagger-apis/acquiring-services/1.0.1.yml
- swagger-apis/acquiring-services/index.html
> GT Dados Abertos (Acquiring Services) Versão 1.0.1

- swagger-apis/investments/1.0.1.yml
- swagger-apis/investments/index.html
> GT Dados abertos: Feat(Investments): versão 1.0.1

- swagger-apis/channels/2.0.1.yml
- swagger-apis/channels/index.html
> GT Dados abertos: Feat(channels): versão 2.0.1

- dictionary/enrollmentCreateFidoRegistrationOptions_v2.csv
- dictionary/enrollmentCreateFidoSigningOptions_v2.csv
- dictionary/enrollmentRegisterFidoCredential_v2.csv
- swagger-apis/enrollments/2.0.0.yml
- swagger-apis/enrollments/index.html
> GT Serviços: Feat(Enrollments) Versão 2.0.0

- dictionary/financingsGetContractsContractIdPayments_v2.csv
- dictionary/financingsGetContractsContractId_v2.csv
- dictionary/financingsGetContracts_v2.csv
- swagger-apis/financings/2.3.0.yml
- swagger-apis/financings/index.html
> GT dados do cliente: Feat(financings): Versão 2.3.0

- dictionary/invoiceFinancingsGetContractsContractIdPayments_v2.csv
- dictionary/invoiceFinancingsGetContractsContractIdScheduledInstalments_v2.csv
- dictionary/invoiceFinancingsGetContractsContractId_v2.csv
- dictionary/invoiceFinancingsGetContracts_v2.csv
- swagger-apis/invoice-financings/2.3.0.yml
- swagger-apis/invoice-financings/index.html
> GT dados do cliente: Feat(invoice financings): Versão 2.3.0

- dictionary/banktFixedIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- swagger-apis/bank-fixed-incomes/1.0.4.yml
- swagger-apis/bank-fixed-incomes/index.html
> GT Serviços: Feat(Bank Fixed Incomes) Nova versão: 1.0.4

- dictionary/creditFixedIncomesGetInvestmentsInvestmentIdBalances_v1.csv
- swagger-apis/credit-fixed-incomes/1.0.3.yml
- swagger-apis/credit-fixed-incomes/index.html
> GT Serviços: Feat(Credit Fixed Incomes) Nova versão: 1.0.3

- swagger-apis/variable-incomes/1.2.1.yml
- swagger-apis/variable-incomes/index.html
> GT Dados do cliente: Feat(Variable incomes) Lançamento da versão 1.2.1

- dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.0.0.csv
- dictionary/automaticPaymentsGetPixRecurringPayments_v2.0.0.csv
- dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.0.0.csv
- dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.0.0.csv
- dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.0.0.csv
- dictionary/automaticPaymentsPostPixRecurringPayments_v2.0.0.csv
- dictionary/automaticPaymentsPostRecurringConsents_v2.0.0.csv
- swagger-apis/automatic-payments/2.0.0.yml
- swagger-apis/automatic-payments/index.html
> GT Serviços: Feat(Automatic Payments): Versão 2.0.0

- dictionary/creditPortabilityGetAccountData_v1.0.0.csv
- dictionary/creditPortabilityGetCreditOperationsContratIdPortabilityEligibility_v1.0.0.csv
- dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
- dictionary/creditPortabilityPostPortabilitiesPortabilityIdCancel_v1.0.0.csv
- dictionary/creditPortabilityPostPortabilitiesPortabilityIdPayment_v1.0.0.csv
- dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
- swagger-apis/credit-portability/1.0.0-beta.1.yml
- swagger-apis/credit-portability/index.html
> GT Portabilidade de Crédito: Feat(Portabilidade de Crédito): Versão 1.0.0-beta.1

- dictionary/creditPortabilityGetAccountData_v1.0.0.csv
- dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
- dictionary/creditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
- dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
- swagger-apis/credit-portability/1.0.0-beta.2.yml
- swagger-apis/credit-portability/index.html
> GT Portabilidade de Crédito: Feat(Portabilidade de Crédito): Versão: 1.0.0-beta.2

- swagger-apis/credit-portability/1.0.0-beta.2.yml
Ajusta link em orientações gerais
> GT Portabilidade de Crédito: Fix(Credit Portability): Ajusta link em orientações gerais

- dictionary/accountsGetAccountsAccountIdBalances_v2.4.2.csv
- dictionary/accountsGetAccountsAccountIdOverdraftLimits_v2.4.2.csv
- dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.4.2.csv
- dictionary/accountsGetAccountsAccountIdTransactions_v2.4.2.csv
- dictionary/accountsGetAccountsAccountId_v2.4.2.csv
- dictionary/accountsGetAccounts_v2.4.2.csv
- swagger-apis/accounts/2.4.2.yml
- swagger-apis/accounts/index.html
> GT Dados do cliente: Feat(Accounts) Versão 2.4.2

- dictionary/treasureTitlesGetInvestmentsInvestmentIdBalances_v1.0.2.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactionsCurrent_v1.0.2.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactions_v1.0.2.csv
- dictionary/treasureTitlesGetInvestmentsInvestmentId_v1.0.2.csv
- dictionary/treasureTitlesGetInvestments_v1.0.2.csv
- swagger-apis/treasure-titles/1.0.2.yml
- swagger-apis/treasure-titles/index.html
> GT Dados do cliente: Feat(Treasure titles): Versão 1.0.2

- dictionary/creditPortabilityGetAccountData_v1.0.0.csv
- dictionary/creditPortabilityGetCreditOperationsContratIdPortabilityEligibility_v1.0.0.csv
- dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
- dictionary/creditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
- dictionary/creditPortabilityPostPortabilitiesPortabilityIdPayment_v1.0.0.csv
- dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
- swagger-apis/credit-portability/1.0.0-beta.3.yml
- swagger-apis/credit-portability/index.html
> GT Portabilidade de Crédito: Feat(Portabilidade de Crédito): Versão: 1.0.0-beta.3
